<?xml version="1.0" encoding="utf-8"?><Database Name="DbSchoolManagementSystem" Class="StudentDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=DbSchoolManagementSystem;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="SchoolManagementSystem.Properties.Settings" SettingsPropertyName="DbSchoolManagementSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudentTable" Member="StudentTables">
    <Type Name="StudentTable">
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FatherId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailiD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Class" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Teacher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CourseFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeePaid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>