<?xml version="1.0" encoding="utf-8"?><Database Name="DbSchoolManagementSystem" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=DbSchoolManagementSystem;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="SchoolManagementSystem.Properties.Settings" SettingsPropertyName="DbSchoolManagementSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UsersTable" Member="UsersTables">
    <Type Name="UsersTable">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>